# Generated by Django 2.2.3 on 2019-07-17 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.TextField(blank=True, max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45)),
                ('product_description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('image1', models.ImageField(blank=True, upload_to='chand_imgs')),
                ('image2', models.ImageField(blank=True, upload_to='chand_imgs')),
                ('image3', models.ImageField(blank=True, upload_to='chand_imgs')),
                ('image4', models.ImageField(blank=True, upload_to='chand_imgs')),
                ('image5', models.ImageField(blank=True, upload_to='chand_imgs')),
                ('product_category_fk', models.ForeignKey(db_column='product_category_fk', on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='chandler.Category')),
            ],
        ),
    ]
