# Generated by Django 2.2.4 on 2019-08-10 08:16

import chandler.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45)),
                ('cate_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chandler.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('coupon_code', models.CharField(max_length=20)),
                ('coupon_description', models.CharField(blank=True, max_length=200, null=True)),
                ('coupon_type', django_enumfield.db.fields.EnumField(default=2, enum=chandler.models.CouponType)),
                ('start_date_coupon', models.DateField(blank=True)),
                ('end_date_coupon', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=50)),
                ('tax_value', models.IntegerField()),
                ('tax_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(max_length=500)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45)),
                ('product_description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('image1', models.ImageField(blank=True, default='noimage.png', upload_to='chand_imgs')),
                ('image2', models.ImageField(blank=True, default='noimage.png', upload_to='chand_imgs')),
                ('image3', models.ImageField(blank=True, default='noimage.png', upload_to='chand_imgs')),
                ('image4', models.ImageField(blank=True, default='noimage.png', upload_to='chand_imgs')),
                ('image5', models.ImageField(blank=True, default='noimage.png', upload_to='chand_imgs')),
                ('product_category_fk', models.ForeignKey(blank=True, db_column='product_category_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pros', to='chandler.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chandler.Cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chandler.Product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, through='chandler.Cart_item', to='chandler.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
    ]
