# Generated by Django 2.2.3 on 2019-07-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default='static/images/noimage.png', upload_to='chand_imgs'),
        ),
    ]
