# Generated by Django 2.2.3 on 2019-07-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chandler', '0002_auto_20190729_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default='/noimage.png', upload_to='chand_imgs'),
        ),
    ]
