# Generated by Django 2.2.4 on 2019-08-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chandler', '0003_auto_20190810_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='in_cart', through='chandler.Cart_item', to='chandler.Product'),
        ),
    ]
