# Generated by Django 2.2.3 on 2019-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chandler', '0003_auto_20190729_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, upload_to='chand_imgs'),
        ),
    ]
