# Generated by Django 2.2.3 on 2019-07-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chandler', '0004_auto_20190729_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default='noimage.png', upload_to='chand_imgs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default='noimage.png', upload_to='chand_imgs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, default='noimage.png', upload_to='chand_imgs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, default='noimage.png', upload_to='chand_imgs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, default='noimage.png', upload_to='chand_imgs'),
        ),
    ]
