# Generated by Django 2.2.3 on 2019-07-30 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chandler', '0005_auto_20190730_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cate_fk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='chandler.Category'),
            preserve_default=False,
        ),
    ]
