# Generated by Django 2.2.3 on 2019-07-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chandler', '0006_category_cate_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chandler.Category'),
        ),
    ]
