# Generated by Django 2.2.4 on 2019-08-16 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chandler', '0006_auto_20190813_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='OrderHistroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=20)),
                ('item_no', models.CharField(max_length=50)),
                ('checksum', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('orderplaced_on', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chandler.Product')),
                ('shippingaddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chandler.ShippingAddress')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
