# Generated by Django 2.2.4 on 2019-08-24 06:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chandler', '0008_auto_20190816_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='product_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='orderhistroy',
            name='shippingaddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chandler.ShippingAddress'),
        ),
    ]
