# Generated by Django 2.2.3 on 2019-07-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chandler', '0008_auto_20190730_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chandler.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category_fk',
            field=models.ForeignKey(blank=True, db_column='product_category_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pros', to='chandler.Category'),
        ),
    ]
