# Generated by Django 2.2.3 on 2019-07-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chandler', '0009_auto_20190730_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
